const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",
  SET_USER: "SET_USER",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIDED: " FETCH_GENDER_FAIDED",

  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAIDED: " FETCH_POSITION_FAIDED",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIDED: " FETCH_ROLE_FAIDED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILDED: "CREATE_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILDED: "DELETE_USER_FAILED",

  DELETE_ORDER: "DELETE_ORDER",
  DELETE_COURSES: "DELETE_COURSES",
  DELETE_VIDEOS: "DELETE_VIDEOS",
  DELETE_TEACHERS: "DELETE_TEACHERS",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILDED: "EDIT_USER_FAILED",

  EDIT_PROFILE_USER_SUCCESS: "EDIT_PROFILE_USER_SUCCESS",
  EDIT_PROFILE_USER_FAILED: "EDIT_PROFILE_USER_FAILED",

  EDIT_ORDER_SUCCESS: "EDIT_ORDER_SUCCESS",
  EDIT_ORDER_FAILDED: "EDIT_ORDER_FAILDED",

  FETCH_ALL_ORDERS_SUCCESS: "FETCH_ALL_ORDERS_SUCCESS",
  FETCH_ALL_ORDERS_FAILDED: "FETCH_ALL_ORDERS_FAILDED",

  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILDED: "FETCH_ALL_USERS_FAILED",
  FETCH_ALL_TEACHERS_SUCCESS: "FETCH_ALL_TEACHERS_SUCCESS",
  FETCH_ALL_TEACHERS_FAILDED: "FETCH_ALL_TEACHERS_FAILED",

  FETCH_TOP_TEACHERS_SUCCESS: "FETCH_TOP_TEACHERS_SUCCESS",
  FETCH_TOP_TEACHERS_FAILDED: "FETCH_TOP_TEACHERS_FAILED",

  FETCH_ALL_TEACHERS_SUCCESS: "FETCH_ALL_TEACHERS_SUCCESS",
  FETCH_ALL_TEACHERS_FAILDED: "FETCH_ALL_TEACHERS_FAILED",

  SAVE_DETAIL_TEACHERS_SUCCESS: "SAVE_DETAIL_TEACHERS_SUCCESS",
  SAVE_DETAIL_TEACHERS_FAILDED: "SAVE_DETAIL_TEACHERS_FAILED",

  FETCH_TEACHERS_REQUIRE_INFOR_START: "FETCH_TEACHERS_REQUIRE_INFOR_START",
  FETCH_TEACHERS_REQUIRE_INFOR_SUCCESS: "FETCH_TEACHERS_REQUIRE_INFOR_SUCCESS",
  FETCH_TEACHERS_REQUIRE_INFOR_FAILDED: " FETCH_TEACHERS_REQUIRE_INFOR_FAILDED",

  //order
  CREATE_ORDER: "CREATE_ORDER",
  GET_ORDER: "GET_ORDER",
  EDIT_ORDER: "EDIT_ORDER",
  STORE_ORDER_DATA: "STORE_ORDER_DATA",

  //Courses
  EDIT_COURSES_SUCCESS: "EDIT_COURSES_SUCCESS",
  EDIT_COURSES_FAILED: "EDIT_COURSES_FAILED",
});

export default actionTypes;
